POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVmOGQ3NmMyNmY5NmY4MTIzOGFlNWM1NSIsImlhdCI6MTYwMzEwNjQ5OH0.BxU1bIhxECP9jTCy-MTq9uenVSu3maP_w9kAAuFxVqI

{
    "url": "String",
    "title": "asd",
    "author": "asdd"
}